POST_METHOD = "POST"
GET_METHOD = "GET"
PUT_METHOD = "PUT"
DELETE_METHOD = "DELETE"
ALL_METHODS = [POST_METHOD, GET_METHOD, PUT_METHOD, DELETE_METHOD]

FIRSTNAME = "firstName"
LASTNAME = "lastName"
SALARY = "salary"
ADDRESS = "address"